'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import CharacterWizard from '@/components/CharacterWizard';

interface GameSystem {
  id: number;
  name: string;
  short_name: string;
  description: string;
  icon: string;
}

function CharacterCreateContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  
  const [gameSystems, setGameSystems] = useState<GameSystem[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedSystem, setSelectedSystem] = useState<number | null>(null);
  const [systemData, setSystemData] = useState<any>(null);
  const [mode, setMode] = useState<'manual' | 'guided' | 'ai_guided' | 'ai_built'>('manual');

  // Get initial params
  const initialSystemId = searchParams.get('game_system_id');
  const initialMode = searchParams.get('mode') as any;

  // Fetch game systems
  useEffect(() => {
    fetch('/api/game-systems?active_only=true')
      .then(r => r.json())
      .then(data => {
        setGameSystems(data.systems || []);
        setLoading(false);
        
        // If system ID provided in URL, use it
        if (initialSystemId) {
          setSelectedSystem(parseInt(initialSystemId));
        }
      })
      .catch(() => setLoading(false));
  }, []);

  // Fetch system data when selected
  useEffect(() => {
    if (selectedSystem) {
      // Fetch system details and character schema in parallel
      Promise.all([
        fetch(`/api/game-systems/${selectedSystem}`).then(r => r.json()),
        fetch(`/api/game-systems/${selectedSystem}/data?category=character_schema`).then(r => r.json())
      ])
        .then(([sysData, schemaData]) => {
          setSystemData({
            ...sysData,
            characterSchema: schemaData.data || { sections: [] }
          });
        })
        .catch(() => {});
    }
  }, [selectedSystem]);

  // Set mode from URL
  useEffect(() => {
    if (initialMode && ['manual', 'guided', 'ai_guided', 'ai_built'].includes(initialMode)) {
      setMode(initialMode);
    }
  }, [initialMode]);

  const handleComplete = (character: any) => {
    router.push('/characters');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-white">Loading...</div>
      </div>
    );
  }

  // No system selected - show picker
  if (!selectedSystem) {
    return (
      <div className="min-h-screen bg-slate-900 p-6">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold text-white mb-6">Choose a Game System</h1>
          
          {/* Mode selector */}
          <div className="mb-6">
            <label className="text-slate-400 text-sm mr-4">Creation Mode:</label>
            <select
              value={mode}
              onChange={(e) => setMode(e.target.value as any)}
              className="px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg text-white"
            >
              <option value="manual">Manual - Fill in all fields yourself</option>
              <option value="guided">Guided - Step-by-step with instructions</option>
              <option value="ai_guided">AI Guided - Some sections generated by AI</option>
              <option value="ai_built">AI Built - AI generates the whole character</option>
            </select>
          </div>
          
          {/* Game system cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {gameSystems.map((sys) => (
              <button
                key={sys.id}
                onClick={() => setSelectedSystem(sys.id)}
                className="p-4 bg-slate-800 rounded-lg text-left hover:bg-slate-700 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <span className="text-2xl">{sys.icon || '🎮'}</span>
                  <div>
                    <h3 className="text-white font-semibold">{sys.name}</h3>
                    {sys.short_name && (
                      <p className="text-slate-400 text-sm">{sys.short_name}</p>
                    )}
                  </div>
                </div>
                {sys.description && (
                  <p className="text-slate-500 text-sm mt-2">{sys.description}</p>
                )}
              </button>
            ))}
          </div>
          
          {gameSystems.length === 0 && (
            <div className="text-center text-slate-400 p-8">
              No game systems found. Import a game system first.
            </div>
          )}
        </div>
      </div>
    );
  }

  // No system data yet
  if (!systemData) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-white">Loading game system...</div>
      </div>
    );
  }

  // Render the wizard
  return (
    <div className="min-h-screen bg-slate-900 p-6">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <button
              onClick={() => setSelectedSystem(null)}
              className="text-purple-400 hover:text-purple-300 text-sm mb-2"
            >
              ← Change Game System
            </button>
            <h1 className="text-2xl font-bold text-white">
              Create Character - {systemData.system?.name || 'Unknown System'}
            </h1>
          </div>
          <div className="text-right">
            <span className="text-purple-400 text-sm capitalize">{mode.replace('_', ' ')}</span>
          </div>
        </div>

        {/* Wizard */}
        <div className="bg-slate-800 rounded-lg p-6">
          <CharacterWizard
            gameSystemId={selectedSystem}
            gameSystemName={systemData.system?.name || ''}
            characterSchema={systemData.characterSchema || { sections: [] }}
            systemConfig={systemData.system?.config ? JSON.parse(systemData.system.config) : {}}
            mode={mode}
            onComplete={handleComplete}
          />
        </div>
      </div>
    </div>
  );
}

export default function CharacterCreatePage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-white">Loading...</div>
      </div>
    }>
      <CharacterCreateContent />
    </Suspense>
  );
}