name: Update Build Info

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Update build hash')"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update hash
        run: |
          echo '{"buildHash": "${{ github.sha }}"}' > build-info.json

      - name: Commit
        run: |
          git config user.name "github-actions"
          git add build-info.json
          git commit -m "Update build hash to ${{ github.sha }}"
          git push
